server:
  error:
    include-stacktrace: never

spring:
  jpa:
    hibernate:
      ddl-auto: update #update
    show-sql: true
  datasource:
    url: jdbc:mysql://localhost:3306/restaurant-db?createDatabaseIfNotExist=true #default port is 3306
    username: root
    #password: password
  #security:
   # user:
    #  name: foo
     # password: foo
